// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
import { Ai, Fetcher } from '@cloudflare/workers-types';

export type Env = {
  ASSETS: Fetcher;
  AI: Ai;
};
